[package]
name = "advent-of-code-2025"
version = "0.1.0"
authors = ["Christoph Laaber"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
derive_more = { version = "2.1.0", features = ["display"] }
